import mongoose from 'mongoose';
import Game from '../models/Game';

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/cassanova';

const games = [
  {
    title: 'Book of Ra',
    slug: 'book-of-ra',
    provider: 'Novomatic',
    category: 'slots',
    subcategory: 'adventure',
    thumbnail: 'https://placehold.co/400x300/1a1a2e/gold?text=Book+of+Ra',
    description: 'Journey to ancient Egypt in this classic slot with expanding symbols and free spins.',
    rtp: 95.1,
    volatility: 'high',
    features: ['Free Spins', 'Expanding Symbols', 'Gamble Feature'],
    minBet: 0.10,
    maxBet: 100,
    isPopular: true,
    isNew: false,
    isFeatured: true,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/book-of-ra',
  },
  {
    title: 'Starburst',
    slug: 'starburst',
    provider: 'NetEnt',
    category: 'slots',
    subcategory: 'classic',
    thumbnail: 'https://placehold.co/400x300/0d0d1a/cyan?text=Starburst',
    description: 'The iconic jewel-themed slot with expanding wilds and re-spins.',
    rtp: 96.1,
    volatility: 'low',
    features: ['Expanding Wilds', 'Re-spins', 'Both-ways Pay'],
    minBet: 0.10,
    maxBet: 100,
    isPopular: true,
    isNew: false,
    isFeatured: true,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/starburst',
  },
  {
    title: 'Mega Moolah',
    slug: 'mega-moolah',
    provider: 'Microgaming',
    category: 'slots',
    subcategory: 'progressive',
    thumbnail: 'https://placehold.co/400x300/1a2e0d/lime?text=Mega+Moolah',
    description: 'The millionaire-maker progressive jackpot slot. Win one of four jackpots!',
    rtp: 88.1,
    volatility: 'medium',
    features: ['Progressive Jackpot', 'Free Spins', 'Wild Multiplier'],
    minBet: 0.25,
    maxBet: 6.25,
    isPopular: true,
    isNew: false,
    isFeatured: true,
    hasJackpot: true,
    jackpotAmount: 5000000,
    demoAvailable: true,
    launchUrl: '/games/mega-moolah',
  },
  {
    title: 'Gonzo\'s Quest',
    slug: 'gonzos-quest',
    provider: 'NetEnt',
    category: 'slots',
    subcategory: 'adventure',
    thumbnail: 'https://placehold.co/400x300/2e1a0d/orange?text=Gonzo\'s+Quest',
    description: 'Join Gonzo on his quest for El Dorado in this avalanche-reels masterpiece.',
    rtp: 95.97,
    volatility: 'medium',
    features: ['Avalanche Reels', 'Free Falls', 'Multipliers'],
    minBet: 0.20,
    maxBet: 50,
    isPopular: true,
    isNew: false,
    isFeatured: false,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/gonzos-quest',
  },
  {
    title: 'European Roulette',
    slug: 'european-roulette',
    provider: 'Evolution Gaming',
    category: 'table-games',
    subcategory: 'roulette',
    thumbnail: 'https://placehold.co/400x300/0d1a2e/gold?text=Roulette',
    description: 'Classic European Roulette with a single zero, giving you the best odds.',
    rtp: 97.3,
    volatility: 'medium',
    features: ['Single Zero', 'La Partage Rule', 'Multiple Bet Types'],
    minBet: 0.50,
    maxBet: 5000,
    isPopular: true,
    isNew: false,
    isFeatured: false,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/european-roulette',
  },
  {
    title: 'Blackjack Classic',
    slug: 'blackjack-classic',
    provider: 'Evolution Gaming',
    category: 'table-games',
    subcategory: 'blackjack',
    thumbnail: 'https://placehold.co/400x300/0a1a0a/green?text=Blackjack',
    description: 'Standard Blackjack with Las Vegas rules. Beat the dealer to 21!',
    rtp: 99.28,
    volatility: 'low',
    features: ['Double Down', 'Split', 'Insurance', 'Surrender'],
    minBet: 1,
    maxBet: 500,
    isPopular: true,
    isNew: false,
    isFeatured: false,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/blackjack-classic',
  },
  {
    title: 'Gates of Olympus',
    slug: 'gates-of-olympus',
    provider: 'Pragmatic Play',
    category: 'slots',
    subcategory: 'mythology',
    thumbnail: 'https://placehold.co/400x300/1e0d2e/purple?text=Gates+of+Olympus',
    description: 'Zeus rules the reels! Tumbling wins and massive multipliers await on Olympus.',
    rtp: 96.5,
    volatility: 'high',
    features: ['Tumble Feature', 'Multiplier Symbols', 'Buy Bonus'],
    minBet: 0.20,
    maxBet: 125,
    isPopular: true,
    isNew: true,
    isFeatured: true,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/gates-of-olympus',
  },
  {
    title: 'Sweet Bonanza',
    slug: 'sweet-bonanza',
    provider: 'Pragmatic Play',
    category: 'slots',
    subcategory: 'candy',
    thumbnail: 'https://placehold.co/400x300/2e0d1a/pink?text=Sweet+Bonanza',
    description: 'A candy-themed slot bursting with fruit symbols, free spins, and bomb multipliers.',
    rtp: 96.48,
    volatility: 'high',
    features: ['Tumble Feature', 'Free Spins', 'Multiplier Bombs', 'Buy Bonus'],
    minBet: 0.20,
    maxBet: 125,
    isPopular: true,
    isNew: true,
    isFeatured: false,
    hasJackpot: false,
    demoAvailable: true,
    launchUrl: '/games/sweet-bonanza',
  },
];

async function seed() {
  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  await Game.deleteMany({});
  console.log('Cleared existing games');

  const inserted = await Game.insertMany(games);
  console.log(`Seeded ${inserted.length} games`);

  await mongoose.disconnect();
  console.log('Done');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
